spring:
  # DB Configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    # druid
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 10
      max-wait: 60000
      time-between-eviction-runs-millis: 300000

  # freemarker
  freemarker:
    cache: false
    request-context-attribute: request
    template-loader-path: classpath:/templates
    prefix: /view/
    suffix: .ftl

  # thymeleaf
  thymeleaf:
    cache: false
    prefix: classpath:/templates/view/
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html

# mybatis
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  check-config-location: true
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080
  servlet:
    context-path: /springbootdemo

# pageHelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql